import { addComment, archiveTask, createTask, reassignTask, routeTask, signOut, updateTask } from "@/app/actions";
import { requireUser, isLead } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { Priority, Role, Status, Team } from "@prisma/client";
import { ThemeToggle } from "./theme-toggle";
const labels:Record<Status,string>={TODO:"To Do",IN_PROGRESS:"In Progress",REVIEW:"Review",DONE:"Done"};
const teams:Record<Team,string>={CREATIVE:"Creative",MARKETING:"Marketing",DEV:"Dev"};
function when(date:Date){return new Intl.DateTimeFormat("en",{month:"short",day:"numeric"}).format(date)}
export default async function Dashboard({searchParams}:{searchParams:Promise<{filter?:string}>}){
 const {filter}=await searchParams;
 const user=await requireUser(); const all=user.role===Role.ADMIN; const lead=isLead(user);
 const where=all?{}:{OR:[{team:user.team!},{creatorId:user.id},{assigneeId:user.id}]};
 const [tasks,users]=await Promise.all([prisma.task.findMany({where,include:{creator:true,assignee:true,comments:{include:{author:true},orderBy:{createdAt:"asc"}}},orderBy:{updatedAt:"desc"}}),prisma.user.findMany({orderBy:{name:"asc"}})]);
 const unfilteredVisible=tasks.filter(t=>!t.isIncoming&&!t.archivedAt); const cutoff=filter==="recent"?new Date(Date.now()-7*864e5):filter==="month"?new Date(new Date().getFullYear(),new Date().getMonth(),1):null; const visible=cutoff?unfilteredVisible.filter(t=>t.createdAt>=cutoff):unfilteredVisible; const incoming=tasks.filter(t=>t.isIncoming && (all || (lead&&t.team===user.team))); const overdue=visible.filter(t=>t.dueDate&&t.dueDate<new Date()&&t.status!==Status.DONE).length;
 const mine=visible.filter(t=>t.assigneeId===user.id); const completed=visible.filter(t=>t.status===Status.DONE).length;
 return <main className="shell"><header><div className="brand"><span className="mark">✓</span><span>TaskFlow</span></div><nav><a className="active" href="#board">Board</a><a href="/reports">Reports</a>{all&&<><a href="/admin">Admin</a><a href="/business">Business</a></>}</nav><div className="user"><ThemeToggle/><span className="avatar">{user.name[0]}</span><span className="user-name">{user.name}</span><form action={signOut}><button className="link">Sign out</button></form></div></header>
 <section className="hero"><div><p className="eyebrow">{all?"COMPANY WORKSPACE":`${teams[user.team!].toUpperCase()} TEAM`}</p><h1>Good {new Date().getHours()<12?"morning":"afternoon"}, {user.name.split(" ")[0]}.</h1><p>Keep work moving, with everyone in the loop.</p></div><details className="new-task"><summary>＋ New task</summary><form action={createTask}><input name="title" placeholder="Task title" required/><textarea name="description" placeholder="A little context goes a long way"/><div className="form-row"><select name="team" defaultValue={user.team??Team.CREATIVE}>{Object.entries(teams).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><select name="priority" defaultValue={Priority.MEDIUM}><option value="LOW">Low priority</option><option value="MEDIUM">Medium priority</option><option value="HIGH">High priority</option></select><input name="dueDate" type="date"/></div><button className="primary">Create task</button></form></details></section>
 <section className="metrics"><article><span>My open tasks</span><strong>{mine.filter(t=>t.status!==Status.DONE).length}</strong><small>Assigned directly to you</small></article><article><span>{all?"Company tasks":"Team tasks"}</span><strong>{visible.filter(t=>all||t.team===user.team).length}</strong><small>Across active work</small></article><article><span>Completed</span><strong>{completed}</strong><small>Visible completed tasks</small></article><article className="attention"><span>Overdue</span><strong>{overdue}</strong><small>Past due and open</small></article>{lead&&<article className="attention"><span>Incoming requests</span><strong>{incoming.length}</strong><small>Needs team routing</small></article>}</section>
 {incoming.length>0&&<section className="incoming"><div><p className="eyebrow">INCOMING QUEUE</p><h2>Requests waiting for {all?"routing":"your team"}</h2></div>{incoming.map(task=>{const assignees=users.filter(u=>u.team===task.team);return <article className="incoming-card" key={task.id}><div><b>{task.title}</b><p>From {task.creator.name} · {teams[task.team]}</p></div><form action={routeTask.bind(null,task.id)}><select name="assigneeId" required defaultValue=""><option disabled value="">Assign to…</option>{assignees.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select><button className="primary">Route task</button></form></article>})}</section>}
 <section id="board" className="board-section"><div className="section-heading"><div><p className="eyebrow">WORKSPACE</p><h2>{all?"Company board":`${teams[user.team!]} board`}</h2></div><div className="filters"><span>Quick filters:</span><a href="/?filter=recent">Recent</a><a href="/?filter=month">This month</a><a href="/">All</a></div></div><div className="board">{Object.values(Status).map(status=><div className="column" key={status}><div className="column-title"><span>{labels[status]}</span><em>{visible.filter(t=>t.status===status).length}</em></div>{visible.filter(t=>t.status===status).map(task=><TaskCard key={task.id} task={task} user={user} users={users}/>)}</div>)}</div></section>
 <section id="reports" className="report"><p className="eyebrow">REPORTS</p><h2>{all?"Company report":lead?"Team report":"My report"}</h2><p className="muted">Completed {completed} of {visible.length} visible tasks.</p><p><a href="/api/report?scope=mine&period=week">This week CSV</a> · <a href="/api/report?scope=mine&period=month">This month CSV</a></p><form action="/api/report" method="get"><input type="hidden" name="scope" value="mine"/><input name="start" type="date" aria-label="Report start date"/> <input name="end" type="date" aria-label="Report end date"/> <button>Export custom range CSV</button></form>{lead&&<a className="secondary" href={`/api/report?scope=${all?"company":"team"}`}>Export {all?"company":"team"} CSV</a>}</section>
 </main>}
function TaskCard({task,user,users}:{task:any;user:any;users:any[]}){const lead=user.role===Role.ADMIN||(user.role===Role.LEAD&&user.team===task.team);const canManage=lead||task.assigneeId===user.id;const late=task.dueDate&&task.dueDate<new Date()&&task.status!==Status.DONE;return <article className="task"><div className="task-meta"><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span><span>{teams[task.team as Team]}</span></div><h3>{task.title}</h3>{task.description&&<p>{task.description}</p>}{late&&<p className="overdue">⚠ Overdue</p>}<div className="task-footer"><span className="avatar small">{task.assignee?.name?.[0]??"?"}</span><span>{task.dueDate?`Due ${when(task.dueDate)}`:"No due date"}</span></div>{lead&&<form className="move" action={reassignTask.bind(null,task.id)}><select name="assigneeId" defaultValue={task.assigneeId??""}>{users.filter(u=>u.team===task.team).map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select><button>Assign</button></form>}{canManage&&<form className="move" action={updateTask.bind(null,task.id)}><select name="status" defaultValue={task.status}>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><button>Move</button></form>}{lead&&<form className="move" action={archiveTask.bind(null,task.id)}><button>Archive</button></form>}<details className="comments"><summary>◌ {task.comments.length} comment{task.comments.length===1?"":"s"}</summary><div>{task.comments.map((c:any)=><p key={c.id}><b>{c.author.name.split(" ")[0]}</b> {c.body}</p>)}</div><form action={addComment.bind(null,task.id)}><input name="body" placeholder="Add an update…" required/><button>Send</button></form></details></article>}
