import { FinancialType, Role } from "@prisma/client";
import { addFinancialEntry, deleteFinancialEntry } from "@/app/actions";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import "./business.css";

const money=(value:number)=>`₹${value.toLocaleString("en-IN")}`;
export default async function BusinessPage(){const admin=await requireUser();if(admin.role!==Role.ADMIN)redirect("/");const [entries,staff]=await Promise.all([prisma.financialEntry.findMany({orderBy:{recordedAt:"desc"}}),prisma.user.findMany({where:{isActive:true},orderBy:{monthlySalary:"desc"}})]);const revenue=entries.filter(x=>x.type===FinancialType.REVENUE).reduce((n,x)=>n+x.amount,0),expenses=entries.filter(x=>x.type===FinancialType.EXPENSE).reduce((n,x)=>n+x.amount,0),payroll=staff.reduce((n,x)=>n+x.monthlySalary,0),profit=revenue-expenses-payroll;return <main className="shell business"><header><div className="brand"><span className="mark">✓</span><span>TaskFlow</span></div><nav><a href="/">Board</a><a href="/reports">Reports</a><a href="/admin">Admin</a><a className="active" href="/business">Business</a></nav><div className="user"><span className="avatar">{admin.name[0]}</span></div></header><section className="hero"><div><p className="eyebrow">BUSINESS INSIGHTS</p><h1>Revenue, costs, and team investment.</h1><p>Track the operational picture alongside delivery performance.</p></div></section><section className="metrics finance-metrics"><Card label="Revenue" value={money(revenue)}/><Card label="Operating expenses" value={money(expenses)}/><Card label="Monthly payroll" value={money(payroll)}/><Card label={profit>=0?"Net profit":"Net loss"} value={money(Math.abs(profit))}/></section><section className="business-grid"><article className="panel"><p className="eyebrow">ADD ENTRY</p><h2>Revenue or expense</h2><form action={addFinancialEntry} className="entry-form"><select name="type"><option value="REVENUE">Revenue</option><option value="EXPENSE">Expense</option></select><input name="category" placeholder="Category (e.g. Software)" required/><input name="amount" type="number" min="1" placeholder="Amount in INR" required/><input name="note" placeholder="Optional note"/><button className="primary">Save entry</button></form></article><article className="panel"><p className="eyebrow">PAYROLL</p><h2>Active team salaries</h2>{staff.map(person=><p className="line" key={person.id}><span>{person.name}<small>{person.role}</small></span><b>{money(person.monthlySalary)}</b></p>)}</article></section><section className="panel"><p className="eyebrow">FINANCIAL LEDGER</p><h2>Revenue & expenses</h2>{entries.length===0?<p className="muted">Add an entry to start tracking business performance.</p>:entries.map(entry=><div className="ledger" key={entry.id}><span className={entry.type===FinancialType.REVENUE?"income":"expense"}>{entry.type}</span><b>{entry.category}</b><small>{entry.note||"No note"} · {entry.recordedAt.toLocaleDateString()}</small><strong>{money(entry.amount)}</strong><form action={deleteFinancialEntry.bind(null,entry.id)}><button>Delete</button></form></div>)}</section></main>}
function Card({label,value}:{label:string;value:string}){return <article><span>{label}</span><strong>{value}</strong><small>Current recorded period</small></article>}
